#!/bin/bash
# attention lancer le navigateur avant
# chromium-browser &
export BROWSER="chromium-browser"
ipython nbconvert CANUM2014.ipynb --to=slides --template output_toggle --post serve --profile=slideshow
